[workspace]
resolver = "2"
members = [
    "kernel/nodejs/tests/napi-echo",
    "kernel/nodejs/tests/napi-controller-errors",
    "sdk/rust",
    "sdk/rust/abi",
    "sdk/rust/macros",
    "templating/rust",
    "analyzer/rust",
    "kernel/rust",
    "cli/rust",
    "modules/console/rust",
    "modules/starlark/rust",
]
