services:
  registry:
    image: node:24
    command: 'sh -c "corepack enable && exec pnpm run telo ./apps/registry"'
    init: true
    volumes:
      - .:/telo
    working_dir: /telo
    env_file:
      - ./apps/registry/.env.local
    ports:
      - "8060:3000"
    environment:
      DB_CONNECTION: "postgres://postgres:postgres@db/registry"
    # depends_on:
    #   db:
    #     condition: service_healthy
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
