kind: Kernel.Module
metadata:
  name: "Config"
  namespace: std
  version: "0.1.0"
exports:
  kinds:
    - EnvironmentVariableStore
    - Variables
    - Secrets
    - Env
---
kind: "Kernel.Definition"
metadata:
  name: "EnvironmentVariableStore"
capability: Kernel.Provider
controllers:
  - pkg:npm/@telorun/config@>=0.1.0?local_path=./nodejs#env-variable-store-controller
schema:
  type: "object"
  properties:
    schema:
      type: "object"
      additionalProperties:
        type: "object"
  required: ["schema"]
  additionalProperties: true
---
kind: "Kernel.Definition"
metadata:
  name: "Variables"
capability: Kernel.Provider
controllers:
  - pkg:npm/@telorun/config@>=0.1.0?local_path=./nodejs#variables-controller
schema:
  type: "object"
  properties:
    storeRef:
      type: "object"
      properties:
        name:
          type: "string"
      required: ["name"]
      additionalProperties: false
    keys:
      type: "object"
      additionalProperties:
        type: "string"
  required: ["storeRef", "keys"]
  additionalProperties: true
---
kind: "Kernel.Definition"
metadata:
  name: "Secrets"
capability: Kernel.Provider
controllers:
  - pkg:npm/@telorun/config@>=0.1.0?local_path=./nodejs#secrets-controller
schema:
  type: "object"
  properties:
    storeRef:
      type: "object"
      properties:
        name:
          type: "string"
      required: ["name"]
      additionalProperties: false
    keys:
      type: "object"
      additionalProperties:
        type: "string"
  required: ["storeRef", "keys"]
  additionalProperties: true
---
kind: "Kernel.Definition"
metadata:
  name: "Env"
capability: Kernel.Provider
controllers:
  - pkg:npm/@telorun/config@>=0.1.0?local_path=./nodejs#env-controller
schema:
  type: object
  properties:
    variables:
      type: object
      additionalProperties:
        type: object
        properties:
          value: {}
          type:
            type: string
            enum: [string, integer, number, boolean]
        required: [value, type]
        additionalProperties: true
    secrets:
      type: object
      additionalProperties:
        type: object
        properties:
          value: {}
          type:
            type: string
            enum: [string, integer, number, boolean]
        required: [value, type]
        additionalProperties: true
  additionalProperties: true
