*
!cli/nodejs
!kernel/nodejs
!analyzer/nodejs
!templating/nodejs
!sdk/nodejs
!scripts
!packages/ide-support
!packages/debug-ui
!package.json
!pnpm-*
!tsconfig.base.json

Dockerfile*
node_modules
dist
