kind: Telo.Application
metadata:
  name: ConfigExample
---
kind: Telo.Import
metadata:
  name: Config
source: ../modules/config
---
kind: Telo.Import
metadata:
  name: Http
source: ../modules/http-server
---
kind: Telo.Import
metadata:
  name: JavaScript
source: ../modules/javascript
---
# Declare an optional variable
kind: Config.Env
metadata:
  name: Config
variables:
  apiBaseUrl:
    env: API_BASE_URL
    type: string
  stripeSecretKey:
    env: STRIPE_SECRET_KEY
    type: string
---
# Consume in another resource
kind: Http.Api
metadata:
  name: PaymentApi
routes:
  - request:
      path: /charge
      method: POST
    handler:
      kind: JavaScript.Script
      code: |
        function main({ apiKey, baseUrl }) {
          return {
            success: true,
          }
        }
    inputs:
      apiKey: "${{ resources.Config.stripeSecretKey }}"
      baseUrl: "${{ resources.Config.apiBaseUrl }}"
    returns:
      - status: 200
        content:
          application/json:
            body:
              message: Payment accepted
---
kind: Http.Server
metadata:
  name: PaymentServer
openapi:
  info:
    title: Payment gateway
    version: 1.0.0
port: 4444
mounts:
  - path: /v1
    type: Http.Api.PaymentApi
