kind: Telo.Application
metadata:
  name: ExampleConsole
  version: 1.0.0
targets:
  - Main
---
kind: Telo.Import
metadata:
  name: Run
source: ../modules/run
---
kind: Telo.Import
metadata:
  name: Console
source: ../modules/console
---
kind: Run.Sequence
metadata:
  name: Main
steps:
  - name: WriteProductInfo
    invoke:
      kind: Console.WriteLine
      metadata:
        name: Result
        module: ExampleConsole
      output: "Product name: Sample Product"
