kind: Kernel.Module
metadata:
  name: ConsoleConfigExample
---
kind: Kernel.Import
metadata:
  name: Config
source: ../modules/config
---
kind: Kernel.Import
metadata:
  name: Console
source: ../modules/console
---
kind: Kernel.Import
metadata:
  name: Flow
source: ../modules/flow
---
kind: Flow.Steps
metadata:
  name: ConsoleConfigExampleFlow
  module: ConsoleConfigExample
trigger:
  event: Kernel.Started
steps:
  - invoke:
      kind: Console.ReadLine
      name: ReadUsername
      prompt: Username
  - invoke:
      kind: Console.ReadLine
      name: ReadPassword
      prompt: Password
  - invoke:
      kind: Console.WriteLine
      name: Result
      output: "Username: ${{ Console.ReadLine.ReadUsername.value }}, Password: ${{ Console.ReadLine.ReadPassword.value }}"
